server.port=8080
spring.application.name=riskmanager

# Direct H2 Embedded Database Pipeline
spring.datasource.url=jdbc:h2:mem:riskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automated live table creation during compilation
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true